name: 'yuzu'
run-name: 'Build yuzu'

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: ./.github/workflows/composite-actions/merge
      - uses: ./.github/workflows/composite-actions/build-msvc

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./.github/workflows/composite-actions/merge.yml
  #     - uses: ./.github/workflows/composite-actions/build-gcc.yml

  release:
    # needs: [build-windows, build-linux]
    needs: [build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "yuzu-windows.7z"
          name: "${{ env.time }}"
          body: "${{ env.body }}"
          tag: "release"
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}